version: '3.5'

# Need to build and tag the example-backend and example-frontend
# images locally with the below names
services:
  backend:
    container_name: backend
    depends_on:
      - nginx
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    expose:
      - 80
    image: backend
    ports:
      - 8080:8080

  frontend:
    container_name: frontend
    depends_on:
      - nginx
    expose:
      - 80
    image: frontend
    ports:
      - 5000:5000

  nginx:
    container_name: nginx
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  postgres:
    container_name: db_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis
