version: '3.5'

# Need to build and tag the example-backend and example-frontend
# images locally with the below names
services:
  backend:
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    image: backend
    ports:
      - 8080:8080

  frontend:
    image: frontend
    ports:
      - 5000:5000

  postgres:
    container_name: db_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres
    restart: unless-stopped

  redis:
    image: redis
